spring:
  application:
    name: pratique
  datasource:
    url: jdbc:h2:file:./data/pratique
    driverClassName: org.h2.Driver
    username: pratique
    password: password
  h2:
    console:
      enable: true
      path: /h2-console
  flyway:
    enabled: false